//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFTPScriptsGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFTPScriptsGenerator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /********************************************************
        /// * This is the back out script to switch back to Momentum
        /// * Momentum Server for pushing the files.
        /// ********************************************************/
        ///
        ///DECLARE
        ///    
        ///    PROCEDURE Back_To_Momentum(   p_DisbType            IN VARCHAR2,
        ///                                  p_Run_Nbr             IN VARCHAR2,
        ///                                  p_SRC_FILE            IN VARCHAR2,
        ///                                  p_New_Dest_Path       IN VARCH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Back_to_Momentum {
            get {
                return ResourceManager.GetString("Back_to_Momentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /***********************************************************************************************************************************************************************************
        ///VALIDATION FOR PAYEE(S):  &apos;#TPDT#&apos;
        ///EXPECTED RESULT:  Should return #NUM# rows
        ///------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///.
        /// </summary>
        internal static string Back_to_Momentum_validation {
            get {
                return ResourceManager.GetString("Back_to_Momentum_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /***************************************************************
        /// * This script switches the payee from Momentum to MOVEIt server 
        /// * for pushing the files through SFTP.
        /// ***************************************************************/
        /// 
        ///DECLARE
        ///    
        ///    PROCEDURE Switch_To_MOVEIt(   p_DisbType            IN VARCHAR2,
        ///                                  p_Run_Nbr             IN VARCHAR2,
        ///                                  p_Release_time        IN VARCHAR2,
        ///                                  p_SRC_FILE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Switch_To_MOVEIt {
            get {
                return ResourceManager.GetString("Switch_To_MOVEIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /***********************************************************************************************************************************************************************************
        ///VALIDATION FOR PAYEE(S):  &apos;#TPDT#&apos;
        ///EXPECTED RESULT:  Should return #NUM# rows
        ///------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///.
        /// </summary>
        internal static string Switch_To_MOVEIt_validation {
            get {
                return ResourceManager.GetString("Switch_To_MOVEIt_validation", resourceCulture);
            }
        }
    }
}
